[2024-06-24T11:13:01.595+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: weather_dag.processing_tasks.extract_data_lviv scheduled__2024-06-22T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
