[2024-06-24T11:35:37.117+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T11:35:37.137+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.processing_tasks.process_data_lviv scheduled__2024-06-22T00:00:00+00:00 [queued]>
[2024-06-24T11:35:37.147+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.processing_tasks.process_data_lviv scheduled__2024-06-22T00:00:00+00:00 [queued]>
[2024-06-24T11:35:37.147+0000] {taskinstance.py:2306} INFO - Starting attempt 10 of 10
[2024-06-24T11:35:37.163+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): processing_tasks.process_data_lviv> on 2024-06-22 00:00:00+00:00
[2024-06-24T11:35:37.170+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1576) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T11:35:37.172+0000] {standard_task_runner.py:63} INFO - Started process 1582 to run task
[2024-06-24T11:35:37.172+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'processing_tasks.process_data_lviv', 'scheduled__2024-06-22T00:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpquhx4_8o']
[2024-06-24T11:35:37.175+0000] {standard_task_runner.py:91} INFO - Job 146: Subtask processing_tasks.process_data_lviv
[2024-06-24T11:35:37.228+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.processing_tasks.process_data_lviv scheduled__2024-06-22T00:00:00+00:00 [running]> on host afc8096e8b86
[2024-06-24T11:35:37.338+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='processing_tasks.process_data_lviv' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-22T00:00:00+00:00'
[2024-06-24T11:35:37.340+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T11:35:37.354+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T11:35:37.354+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag.py", line 22, in _process_weather
    timestamp = info["dt"]
                ~~~~^^^^^^
KeyError: 'dt'
[2024-06-24T11:35:37.364+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=processing_tasks.process_data_lviv, run_id=scheduled__2024-06-22T00:00:00+00:00, execution_date=20240622T000000, start_date=20240624T113537, end_date=20240624T113537
[2024-06-24T11:35:37.380+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 146 for task processing_tasks.process_data_lviv ('dt'; 1582)
[2024-06-24T11:35:37.427+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-24T11:35:37.438+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-06-24T11:35:37.460+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T11:35:37.465+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
