[2024-06-24T11:34:53.188+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T11:34:53.218+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.processing_tasks.process_data_lviv scheduled__2024-06-22T00:00:00+00:00 [queued]>
[2024-06-24T11:34:53.232+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.processing_tasks.process_data_lviv scheduled__2024-06-22T00:00:00+00:00 [queued]>
[2024-06-24T11:34:53.232+0000] {taskinstance.py:2306} INFO - Starting attempt 9 of 9
[2024-06-24T11:34:53.257+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): processing_tasks.process_data_lviv> on 2024-06-22 00:00:00+00:00
[2024-06-24T11:34:53.266+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1546) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T11:34:53.269+0000] {standard_task_runner.py:63} INFO - Started process 1552 to run task
[2024-06-24T11:34:53.271+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'processing_tasks.process_data_lviv', 'scheduled__2024-06-22T00:00:00+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpijlwd6i2']
[2024-06-24T11:34:53.276+0000] {standard_task_runner.py:91} INFO - Job 140: Subtask processing_tasks.process_data_lviv
[2024-06-24T11:34:53.358+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.processing_tasks.process_data_lviv scheduled__2024-06-22T00:00:00+00:00 [running]> on host afc8096e8b86
[2024-06-24T11:34:53.505+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='processing_tasks.process_data_lviv' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-22T00:00:00+00:00'
[2024-06-24T11:34:53.509+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T11:34:53.526+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T11:34:53.527+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag.py", line 22, in _process_weather
    timestamp = info["current"]["dt"]
                ~~~~^^^^^^^^^^^
KeyError: 'current'
[2024-06-24T11:34:53.542+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=processing_tasks.process_data_lviv, run_id=scheduled__2024-06-22T00:00:00+00:00, execution_date=20240622T000000, start_date=20240624T113453, end_date=20240624T113453
[2024-06-24T11:34:53.567+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 140 for task processing_tasks.process_data_lviv ('current'; 1552)
[2024-06-24T11:34:53.606+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-24T11:34:53.623+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-06-24T11:34:53.650+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T11:34:53.658+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
